name: Android Appium Tests on macOS

on:
  push:
    branches: [main]
  pull_request:

jobs:
  android-tests:
    runs-on: macos-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Checkout the project
        uses: actions/checkout@v3

      - name: Setup Appium
        run: |
          npm install -g appium@1.22
          appium -v
          nohup appium > /dev/null 2>&1 &

      - name: Run tests
        uses: reactive circus/android-emulator-runner@v2
        with:
          api-level: 29
          script: mvn clean test
