name: Android Appium Tests on macOS

on:
  push:
    branches: [main]
  pull_request:

jobs:
  android-tests:
    runs-on: macos-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Checkout the project
        uses: actions/checkout@v3

      - name: Setup Node and Appium
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and start Appium
        run: |
          npm install -g appium@2.18
          appium driver install uiautomator2
          nohup appium > appium.log 2>&1 &
          echo "Appium started"

      - name: Run Android Tests with Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          profile: Pixel_3a
          script: |
            adb wait-for-device
            boot_completed=""
            until [[ "$boot_completed" == "1" ]]; do
              boot_completed=$(adb shell getprop sys.boot_completed | tr -d '\r')
              echo "Waiting for emulator to boot..."
              sleep 5
            done
            echo "Emulator is ready"
            mvn clean test
